### PR TITLE
List of citing papers #111

### PR DESCRIPTION
**Pull request by Havaldar**
Pull request to address Issue #111 

- standard plain text links of all works citing pyABC through DOI: 10.1093/bioinformatics/bty361
- DOI links used instead of IDs for easier access

### CODE REVIEW

**Comment by yannikschaelte** [comment]
Hi @Havaldar , thanks a lot, that looks great. I changed the target to another branch from which we can then merge to develop. @elbaraim could you have a short look and then make a PR to develop? Also, it would be great to link to this page in the documentation.

**Comment by yannikschaelte** [comment]
And please move the file into the documentation subfolder.

**Comment by Havaldar** [comment]
@yannikschaelte no problem at all, happy to help! I moved the file to doc/ lmk if there's anything else I can do. Also I used https://www.researchgate.net/publication/325178486_pyABC_distributed_likelihood-free_inference/citations to get the citations and ignored all preprint and theses (essentially only papers with DOI link), if thats not appropriate, please let me know and I shall do the needful.

**Comment by elbaraim** [comment]
Thank you very much @Havaldar for putting together the list.

Could you please add the following PhD thesis?
- Raynal, Louis. Bayesian statistical inference for intractable likelihood models. Diss. Université Montpellier, 2019.
- Kumberger, Peter Johannes Manuel Eduard. Quantifying the Impact of Cell-to-Cell Transmission on Viral Spread. Diss. 2019.
- Klinger, Emmanuel G. Approximate Bayesian Model Selection for Local Cortical Networks at Cellular Resolution. Diss. Technische Universität München, 2018.

**Pull request merged**
