### PR TITLE
Update deploy.yml

### PR DESCRIPTION
**Pull request by stephanmg**
Upgrade actions/checkout@v2 -> actions/checkout@v4.

### CODE REVIEW

**Review by arrjon — APPROVED** [review]
lgtm

**Comment by stephanmg** [comment]
Associated with the deploy.yml - API keys need to re-generated, otherwise deploy GHA will fail.

**Comment by arrjon** [comment]
> Associated with the deploy.yml - API keys need to re-generated, otherwise deploy GHA will fail.

@yannikschaelte could you give us access?

**Comment by stephanmg** [comment]
@arrjon check please

**Pull request merged**
