### PR TITLE
add the functionality to evaluate the model using boundry values of p…

### PR DESCRIPTION
**Pull request by EmadAlamoudi**
closing #353

### CODE REVIEW

**Comment by yannikschaelte** [comment]
@EmadAlamoudi Should I review this?

**Comment by EmadAlamoudi** [comment]
It is done by me. However, I'm not sure how beneficial this to other users, what do you think?

**Comment by yannikschaelte** [comment]
if it helps, it never hurts to have some utility functions somewhere

**Comment by yannikschaelte** [comment]
@EmadAlamoudi what is the status here?

**Review by yannikschaelte — CHANGES_REQUESTED** [review]
merge-in needed to resolve conflicts

**Comment by stephanmg** [comment]
@yannikschaelte what's left here?

**Review by stephanmg — APPROVED** [review]

**Review by arrjon — APPROVED** [review]
LGTM

**Pull request merged**
